auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: BeiYuu.com
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: http://wuzhiweiallen.github.io/
feed: /atom.xml
author_info: <a href="http://beiyuu.com/">BeiYuu</a>
