auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: http://wuzhiweiallen.github.io
baseurl: /blog
url: http://wuzhiweiallen.github.io
feed: /atom.xml
author_info: <a href="http://wuzhiweiallen.github.io/">zhiweiAllen</a>
