auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: :title
description: |
  Another fine responsive  
  site template freebie  
  crafted by [HTML5 UP](http://html5up.net)
title: Spectral
baseurl: /blog
url: http://wuzhiweiallen.github.io
feed: /atom.xml
author_info: <a href="http://wuzhiweiallen.github.io/">zhiweiAllen</a>
