auto: true

markdown: kramdown
pygments: true
paginate: 8

description: |
  Another fine responsive  
  site template freebie  
  crafted by [HTML5 UP](http://html5up.net)
title: Spectral
baseurl: /blog
url: http://wuzhiweiallen.github.io/blog
feed: /atom.xml
author_info: <a href="http://wuzhiweiallen.github.io/blog">zhiweiAllen</a>
